apiVersion: apps/v1
kind: Deployment
metadata:
  name: photo-app-deploy
  namespace: photo-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: photo-label
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: photo-label
    spec:
    #   affinity:
    #     nodeAffinity:
    #       requiredDuringSchedulingIgnoredDuringExecution:
    #         nodeSelectorTerms:
    #           - matchExpressions:
    #               - key: node
    #                 operator: In
    #                 values: 
    #                   - worker
    #       preferredDuringSchedulingIgnoredDuringExecution:
    #       - weight: 5
    #         preference:
    #           matchExpressions:
    #           - key: kubernetes.io/os
    #             operator: In
    #             values: 
    #               - linux
    #       - weight: 10
    #         preference:
    #           matchExpressions:
    #           - key: node2
    #             operator: In
    #             values: 
    #               - top
      tolerations:
      - key: "env"
        operator: "Equal"
        value: "production"
        effect: "NoSchedule"
      containers:
        - name: photo-cont
          image: suryaa112003/photo-studio:v1.1.0
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          env:
          - name: MONGO_URI
            valueFrom:
              secretKeyRef:
                name: photo-secret
                key: url
          - name: MONGODB_AUTH_URI
            valueFrom:
              secretKeyRef:
                name: photo-secret
                key: auth_url
          - name: MONGODB_FEEDBACK_URI
            valueFrom:
              secretKeyRef:
                name: photo-secret
                key: feedback_url

---
apiVersion: v1
kind: Service
metadata:
  name: photo-service
  namespace: photo-ns
spec:
  selector:
    app: photo-label
  ports:
    - port: 3002
      targetPort: 3000
  type: NodePort

---

apiVersion: v1
kind: Secret
metadata:
  name: photo-secret
  namespace: photo-ns
type: Opaque
stringData:
  url: mongodb://photo-mongo-service:27017
  auth_url: mongodb://photo-mongo-service:27017/artgallery
  feedback_url: mongodb://photo-mongo-service:27017/artgallery